#!/bin/bash

# Halt on error
set -e

find "$PAGEGEN_TARGET_DIR" -type f -exec chmod 644 {} \;
find "$PAGEGEN_TARGET_DIR" -type d -exec chmod 755 {} \;

rsync -ap -e "ssh -i /home/oliver/.ssh/id_ed25519" "$PAGEGEN_TARGET_DIR/" 'phnd@login.domeneshop.no:filaments.phnd.net/'

